// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToNotificationsWS() {
  return window['go']['main']['App']['ConnectToNotificationsWS']();
}

export function ConnectToWS() {
  return window['go']['main']['App']['ConnectToWS']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateMeetingRoom(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateMeetingRoom'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAccessToken() {
  return window['go']['main']['App']['GetAccessToken']();
}

export function GetContacts(arg1) {
  return window['go']['main']['App']['GetContacts'](arg1);
}

export function GetLoggedInUserData() {
  return window['go']['main']['App']['GetLoggedInUserData']();
}

export function GetMyRooms() {
  return window['go']['main']['App']['GetMyRooms']();
}

export function GetOnlineContacts() {
  return window['go']['main']['App']['GetOnlineContacts']();
}

export function GetRoomDetails(arg1) {
  return window['go']['main']['App']['GetRoomDetails'](arg1);
}

export function GetRoomTurnCred(arg1) {
  return window['go']['main']['App']['GetRoomTurnCred'](arg1);
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function LoginWithEmail(arg1, arg2) {
  return window['go']['main']['App']['LoginWithEmail'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MarkAllNotificationsAsRead(arg1) {
  return window['go']['main']['App']['MarkAllNotificationsAsRead'](arg1);
}

export function MarkNotificationAsRead(arg1) {
  return window['go']['main']['App']['MarkNotificationAsRead'](arg1);
}

export function OnlineWSAddr() {
  return window['go']['main']['App']['OnlineWSAddr']();
}

export function SendChatReadWsMsg(arg1) {
  return window['go']['main']['App']['SendChatReadWsMsg'](arg1);
}

export function SendOnlineWsMsg(arg1) {
  return window['go']['main']['App']['SendOnlineWsMsg'](arg1);
}
