// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {webrtc} from '../models';
import {Auth} from '../models';
import {chat} from '../models';

export function ConnectToNotificationsWS():Promise<void>;

export function ConnectToWS():Promise<string>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateMeetingRoom(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:number):Promise<webrtc.Response_Desktop_Wails_Gigawrks_controllers_webrtc_RoomCreateResponse_>;

export function GetAccessToken():Promise<string>;

export function GetContacts(arg1:Record<string, string>):Promise<Array<Auth.Contact>>;

export function GetLoggedInUserData():Promise<Auth.User>;

export function GetMyRooms():Promise<webrtc.Response___Desktop_Wails_Gigawrks_controllers_webrtc_RoomCreateResponse_>;

export function GetOnlineContacts():Promise<Array<number>>;

export function GetRoomDetails(arg1:string):Promise<webrtc.Response_Desktop_Wails_Gigawrks_controllers_webrtc_RoomCreateResponse_>;

export function GetRoomTurnCred(arg1:string):Promise<webrtc.Response_Desktop_Wails_Gigawrks_controllers_webrtc_RoomCredResponse_>;

export function IsLoggedIn():Promise<number>;

export function LoginWithEmail(arg1:string,arg2:string):Promise<string>;

export function Logout():Promise<boolean>;

export function MarkAllNotificationsAsRead(arg1:string):Promise<void>;

export function MarkNotificationAsRead(arg1:string):Promise<void>;

export function OnlineWSAddr():Promise<string>;

export function SendChatReadWsMsg(arg1:number):Promise<string>;

export function SendOnlineWsMsg(arg1:chat.OnlineWsMessage):Promise<string>;
